//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_RK_RKDCB
    {
        public string ID { get; set; }
        public string SJBMC { get; set; }
        public string ZBID { get; set; }
        public string CLID { get; set; }
        public string CLBH { get; set; }
        public string CLMC { get; set; }
        public string GGXH { get; set; }
        public string DW { get; set; }
        public Nullable<decimal> SL { get; set; }
        public Nullable<decimal> DJ { get; set; }
        public Nullable<decimal> HJ { get; set; }
        public Nullable<decimal> YFJE { get; set; }
        public string SCPH { get; set; }
        public string SCPHBZ { get; set; }
        public string BZ { get; set; }
        public Nullable<decimal> HTSL { get; set; }
        public Nullable<decimal> HTDJ { get; set; }
        public string SFHTKZCL { get; set; }
        public string SFJHKZCL { get; set; }
        public Nullable<decimal> JHDJ { get; set; }
        public int pid { get; set; }
        public string SFYDJHCL { get; set; }
        public string YDJHBH { get; set; }
    
        public virtual T_RK_RKD T_RK_RKD { get; set; }
    }
}
