//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_RK_RKD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_RK_RKD()
        {
            this.T_RK_RKDCB = new HashSet<T_RK_RKDCB>();
        }
    
        public string ID { get; set; }
        public string SJBMC { get; set; }
        public string XMID { get; set; }
        public string RKDH { get; set; }
        public Nullable<System.DateTime> DJRQ { get; set; }
        public string ZJLB_ID { get; set; }
        public string ZJLB { get; set; }
        public string DBDW_ID { get; set; }
        public string DBDWMC { get; set; }
        public string HT_ID { get; set; }
        public string HTBH { get; set; }
        public string Supplier_ID { get; set; }
        public string SupplierName { get; set; }
        public string Lldw_ID { get; set; }
        public string LldwName { get; set; }
        public string ZT { get; set; }
        public string BZ { get; set; }
        public string LRR { get; set; }
        public Nullable<System.DateTime> LRRQ { get; set; }
        public string SHR { get; set; }
        public Nullable<System.DateTime> SHRQ { get; set; }
        public string SHBZ { get; set; }
        public string SFZJZC { get; set; }
        public string SFCZ { get; set; }
        public string GLRKDId { get; set; }
        public string SFCZRKD { get; set; }
        public string GLYRKDId { get; set; }
        public string JH_ID { get; set; }
        public string JHDH { get; set; }
        public int pid { get; set; }
        public string FJ { get; set; }
        public Nullable<int> f_DJLXZT { get; set; }
        public string SDRKDH { get; set; }
        public string Add1 { get; set; }
        public string Add2 { get; set; }
        public string Add3 { get; set; }
        public string Add4 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_RK_RKDCB> T_RK_RKDCB { get; set; }
    }
}
